import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { FaRegCheckCircle } from "react-icons/fa";
import { getAboutus, getAboutusteams, getmissionvission, getSiteData } from "@/lib/functions";
import InnerBanner from "@/components/InnerBanner/InnerBanner";


export async function generatemetadata() {
  return {
    title: "About Us",
    description: "Generated by R R Grow Wealth.",
  };
}

export default async function AboutUs() {
  const siteSettings = await getSiteData();
  const missionvission = await getmissionvission();
  const teams = await getAboutusteams();
  const aboutus = await getAboutus();

  function createMarkup(item) {
    return { __html: item || "" };
  }

  return (
    <div>
      {/* Hero Section */}

      <InnerBanner pageName="About Us" />

      {/* Introduction Section */}
      

      {/* About Us Detailed Section */}
      <div className="">
        <div className="max-w-screen-xl mx-auto main_section">
          <section className="grid grid-cols-1 md:grid-cols-2 gap-0 mb-6 items-center">
            <div className="relative">
              <Image
                src={aboutus[0]?.image?.url}
                alt="About Us"
                width={550}
                height={550}
                className="rounded-xl  shadow-lg"
              />
            </div>
            <div>
              <h2 className="text-3xl text-black md:text-4xl font-bold mb-6">
                {aboutus[0]?.title}
              </h2>
              <div
                dangerouslySetInnerHTML={createMarkup(aboutus[0]?.description)}
                className="text-black mb-6"
              />
            </div>
          </section>
        </div>
      </div>

      {/* Mission, Vision, Core Values */}
      <div className="bg-[#b2b2b21f]">
        <div className="max-w-screen-xl mx-auto main_section">
        <section className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
          <div className="group bg-[var(--rv-primary)] p-6 rounded-xl shadow-lg hover:scale-105 transition-transform">
            <h3 className="text-2xl font-bold text-white my-3">Our Mission</h3>
            <p className="text-gray-100">At Wealth Matrix, our mission is to empower professionals and entrepreneurs to take charge of their financial future through personalized, strategy-driven wealth planning.</p>
<p className="text-gray-100">We design customized, technology-enabled solutions that help our clients grow, protect, and fully enjoy their wealth — with clarity, confidence, and purpose.</p>
<p className="text-gray-100">By bridging the gap between income and impact, we turn financial potential into true freedom, legacy, and peace of mind — through expert guidance and deep, relationship-driven service.</p>
          
          </div>
          <div className="group bg-[var(--rv-primary)] p-6 rounded-xl shadow-lg hover:scale-105 transition-transform">
            <h3 className="text-2xl font-bold text-white my-3">Our Vision</h3>
             <p className="text-gray-100">We envision a future where wealth is not just accumulated
but aligned with purpose.</p>
<p className="text-gray-100">At Wealth Matrix, our vision is to redefine wealth management by helping our clients achieve financial freedom, time ownership, and the ability to live meaningfully, without compromise.</p>
<p className="text-gray-100">We aspire to be the most trusted wealth management partner for Professionals, Entrepreneurs and families empowering them to build lasting prosperity, create enduring legacies, and focus on what truly matters: family, dreams, and peace of mind.</p>
          
          </div>
        </section>

        {/* <section className="mb-16">
          <h3 className="text-3xl font-semibold text-[var(--rv-primary)] text-center mb-6">
            Core Values
          </h3>
          <p className="text-center max-w-3xl mx-auto text-gray-700 mb-4">
            We firmly believe that our Core Values have served as the Cornerstone for the Expansion and Success of our Company.
          </p>
          <ul className="grid sm:grid-cols-2 md:grid-cols-3 gap-4 text-center max-w-4xl mx-auto">
            {[
              "Financial Education",
              "Commitment",
              "Speed",
              "Transparency",
              "Client Centric Approach",
            ].map((value, i) => (
              <li
                key={i}
                className="bg-gray-100 p-4 rounded-lg shadow text-[var(--rv-primary)] font-semibold"
              >
                {value}
              </li>
            ))}
          </ul>
        </section> */}
      </div>
      </div>

      {/* Team Section */}
      <div className="">
        <div className="max-w-screen-xl mx-auto main_section">
          <section className="mb-20">
            <h2 className="text-2xl md:text-4xl lg:text-5xl font-bold text-[var(--rv-primary)] mb-12 text-center">
              Meet the Minds Powering the Future of Wealth Management
            </h2>
            <div className="group bg-[var(--rv-primary)] p-8 rounded-xl shadow-lg transition-transform transform hover:scale-105 hover:shadow-2xl mb-10">
              <div className="grid md:grid-cols-6 justify-center gap-5">
                <div className="md:col-span-2">
                  <Image
                    src={teams[0]?.image?.url}
                    alt={teams[0]?.name}
                    width={380}
                    height={380}
                    className="rounded grayscale group-hover:grayscale-0 transition-all mr-4"
                  />
                </div>
                <div className="md:col-span-4">
                  <h3 className="text-2xl font-bold text-white mb-4">{teams[0]?.name}</h3>
                  <div
                    dangerouslySetInnerHTML={createMarkup(teams[0]?.description)}
                    className="text-gray-100 mb-4"
                  />
                  {/* <h4 className="text-xl font-semibold text-white mb-2">Quick Bio</h4>
                  <ul className="list-disc pl-5 space-y-2 text-gray-100">
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      CFP (FPSB - Financial Planning Standard Board, USA)
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      CFGP (AAFM - American Academy of Financial Management)
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      30+ Certification courses related to Financial Markets (BSE, NSE, AMFI, etc.)
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      B.Com (South Gujarat University)
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      Author of the book "Mera Wealth Plan"
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      Writes financial articles for Divyabhaskar, Gujarat Samachar, Gujarat Guardian
                    </li>
                  </ul> */}
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>

      {/* Call to Action Section */}
      <div className="bg-[#b2b2b21f]">
        <div className="max-w-screen-xl mx-auto main_section">
        <section className="text-center">
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Join Us on a Journey to Infinite Growth!
          </h2>
          <p className="text-gray-700 max-w-3xl mx-auto mb-8">
            At {siteSettings?.websiteName}, we don’t just manage wealth—we shape financial futures. Join us in transforming financial growth for business owners across India. Together, we’ll redefine what’s possible.
          </p>
          <Link href="/contact-us">
            <button className="bg-[var(--rv-primary)] text-white sm:text-lg md:text-lg font-bold px-4 py-2 rounded-lg hover:bg-[var(--rv-primary)] transition-all px-5 py-2 cursor-pointer">
              Get Started
            </button>
          </Link>
        </section>
      </div>
      </div>
    </div>
  );
}
